RcppExports = """
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Merge data frame columns
#' @title Merge data frame columns
#' @description TBD
#' @param df Dataframe
#' @param cols Vector
#' @param sep Character seperator
#' @export
merge_columns_c <- function(df, cols, sep = ".") {
    .Call('_rENA_merge_columns_c', PACKAGE = 'rENA', df, cols, sep)
}

#' Upper Triangle from Vector
#'
#' @title vector to upper triangle
#' @description TBD
#' @param v [TBD]
#' @export
vector_to_ut <- function(v) {
    .Call('_rENA_vector_to_ut', PACKAGE = 'rENA', v)
}

svector_to_ut <- function(v) {
    .Call('_rENA_svector_to_ut', PACKAGE = 'rENA', v)
}

rows_to_co_occurrences <- function(df, binary = TRUE) {
    .Call('_rENA_rows_to_co_occurrences', PACKAGE = 'rENA', df, binary)
}

ref_window_df <- function(df, windowSize = 1, windowForward = 0, binary = TRUE, binaryStanzas = FALSE) {
    .Call('_rENA_ref_window_df', PACKAGE = 'rENA', df, windowSize, windowForward, binary, binaryStanzas)
}

ref_window_lag <- function(df, windowSize = 0L, binary = TRUE) {
    .Call('_rENA_ref_window_lag', PACKAGE = 'rENA', df, windowSize, binary)
}

#' Sphere norm
#' @title Sphere norm
#' @description TBD
#' @param dfM Dataframe
#' @export
fun_sphere_norm <- function(dfM) {
    .Call('_rENA_fun_sphere_norm', PACKAGE = 'rENA', dfM)
}

#' Non sphere norm
#'
#' @title Non sphere norm
#' @description TBD
#' @param dfM Dataframe
#' @export
fun_skip_sphere_norm <- function(dfM) {
    .Call('_rENA_fun_skip_sphere_norm', PACKAGE = 'rENA', dfM)
}

center_data_c <- function(values) {
    .Call('_rENA_center_data_c', PACKAGE = 'rENA', values)
}

triIndices <- function(len, row = -1L) {
    .Call('_rENA_triIndices', PACKAGE = 'rENA', len, row)
}

lws_lsq_positions <- function(adjMats, t, numDims) {
    .Call('_rENA_lws_lsq_positions', PACKAGE = 'rENA', adjMats, t, numDims)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_rENA_RcppExport_registerCCallable', PACKAGE = 'rENA')
})

"""